encoredev/homebrew-tap

Formula/encore.rb

This commit bumps the Encore version to v1.9.3

Release Encore v1.9.3

---

Formula/encore.rb

This commit bumps the Encore version to v1.9.4

Release Encore v1.9.4

---

Formula/encore.rb

This commit bumps the Encore version to v1.10.0

Release Encore v1.10.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.10.1

Release Encore v1.10.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.10.2

Release Encore v1.10.2

---

Formula/encore.rb

This commit bumps the Encore version to v1.10.3

Release Encore v1.10.3

---

Formula/encore.rb

This commit bumps the Encore version to v1.10.4

Release Encore v1.10.4

---

Formula/encore.rb

This commit bumps the Encore version to v1.10.5

Release Encore v1.10.5

---

Formula/encore.rb

This commit bumps the Encore version to v1.10.6

Release Encore v1.10.6

---

Formula/encore.rb

This commit bumps the Encore version to v1.11.0

Release Encore v1.11.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.11.1

Release Encore v1.11.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.12.0

Release Encore v1.12.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.12.1

Release Encore v1.12.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.13.0

Release Encore v1.13.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.13.1

Release Encore v1.13.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.13.2

Release Encore v1.13.2

---

Formula/encore.rb

This commit bumps the Encore version to v1.13.4

Release Encore v1.13.4

---

Formula/encore.rb

This commit bumps the Encore version to v1.14.0

Release Encore v1.14.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.14.1

Release Encore v1.14.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.14.2

Release Encore v1.14.2

---

Formula/encore.rb

This commit bumps the Encore version to v1.14.3

Release Encore v1.14.3

---

Formula/encore.rb

This commit bumps the Encore version to v1.14.4

Release Encore v1.14.4

---

Formula/encore.rb

This commit bumps the Encore version to v1.14.5

Release Encore v1.14.5

---

Formula/encore.rb

This commit bumps the Encore version to v1.15.0

Release Encore v1.15.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.16.0

Release Encore v1.16.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.16.1

Release Encore v1.16.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.16.3

Release Encore v1.16.3

---

Formula/encore.rb

This commit bumps the Encore version to v1.17.0

Release Encore v1.17.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.18.0

Release Encore v1.18.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.20.0

Release Encore v1.20.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.20.1

Release Encore v1.20.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.20.4

Release Encore v1.20.4

---

Formula/encore.rb

This commit bumps the Encore version to v1.21.0

Release Encore v1.21.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.21.1

Release Encore v1.21.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.21.2

Release Encore v1.21.2

---

Formula/encore.rb

This commit bumps the Encore version to v1.22.0

Release Encore v1.22.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.22.1

Release Encore v1.22.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.22.2

Release Encore v1.22.2

---

Formula/encore.rb

This commit bumps the Encore version to v1.22.3

Release Encore v1.22.3

---

Formula/encore.rb

This commit bumps the Encore version to v1.22.4

Release Encore v1.22.4

---

Formula/encore.rb

This commit bumps the Encore version to v1.23.0

Release Encore v1.23.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.23.2

Release Encore v1.23.2

---

Formula/encore.rb

This commit bumps the Encore version to v1.23.3

Release Encore v1.23.3

---

Formula/encore.rb

This commit bumps the Encore version to v1.24.0

Release Encore v1.24.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.25.0

Release Encore v1.25.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.25.2

Release Encore v1.25.2

---

Formula/encore.rb

This commit bumps the Encore version to v1.26.0

Release Encore v1.26.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.27.1

Release Encore v1.27.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.27.4

Release Encore v1.27.4

---

Formula/encore.rb

This commit bumps the Encore version to v1.27.5

Release Encore v1.27.5

---

Formula/encore.rb

This commit bumps the Encore version to v1.27.6

Release Encore v1.27.6

---

Formula/encore.rb

This commit bumps the Encore version to v1.27.7

Release Encore v1.27.7

---

Formula/encore.rb

This commit bumps the Encore version to v1.28.0

Release Encore v1.28.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.29.0

Release Encore v1.29.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.29.1

Release Encore v1.29.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.29.3

Release Encore v1.29.3

---

Formula/encore.rb

This commit bumps the Encore version to v1.29.4

Release Encore v1.29.4

---

Formula/encore.rb

This commit bumps the Encore version to v1.29.5

Release Encore v1.29.5

---

Formula/encore.rb

This commit bumps the Encore version to v1.29.6

Release Encore v1.29.6

---

Formula/encore.rb

This commit bumps the Encore version to v1.29.7

Release Encore v1.29.7

---

Formula/encore.rb

This commit bumps the Encore version to v1.30.0

Release Encore v1.30.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.31.0

Release Encore v1.31.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.31.1

Release Encore v1.31.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.31.2

Release Encore v1.31.2

---

Formula/encore.rb

This commit bumps the Encore version to v1.33.1

Release Encore v1.33.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.33.5

Release Encore v1.33.5

---

Formula/encore.rb

This commit bumps the Encore version to v1.33.6

Release Encore v1.33.6

---

Formula/encore.rb

This commit bumps the Encore version to v1.34.0

Release Encore v1.34.0

---

Formula/encore.rb

This commit bumps the Encore version to v1.34.1

Release Encore v1.34.1

---

Formula/encore.rb

This commit bumps the Encore version to v1.34.2

Release Encore v1.34.2
